"""add column_statistics

Revision ID: 28e04978099c
Revises: 0001_init_schema
Create Date: 2026-02-21 00:46:24.684915

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '28e04978099c'
down_revision = '0001_init_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('outlier_count', sa.Integer(), nullable=True),
    sa.Column('outlier_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['dataset_columns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('column_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_statistics')
    # ### end Alembic commands ###