"""add ingestion lifecycle tracking

Revision ID: 53a8723469d9
Revises: 23995d329c14
Create Date: 2026-02-21 12:41:46.677468

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '53a8723469d9'
down_revision = '23995d329c14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.add_column('ingestion_runs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion_runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion_runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.drop_index('ix_ingestion_runs_dataset_id', table_name='ingestion_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ingestion_runs_dataset_id', 'ingestion_runs', ['dataset_id'], unique=False)
    op.drop_column('ingestion_runs', 'duration_ms')
    op.drop_column('ingestion_runs', 'completed_at')
    op.drop_column('ingestion_runs', 'started_at')
    op.drop_column('ingestion_runs', 'error_message')
    # ### end Alembic commands ###